### ISSUE TITLE
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by Do1SKL** [laneboyerre/meshtastic_chat_desktop#3]
Message appears when attempting to start !!!!!!!!!!!!!!!!!
-----------------------------------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/dks384/meshtastic_chat_desktop/meshtastic_chat_desktop.py", line 3, in < module >
    import tkinter as tk
  File "/usr/local/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'

-------------------------------------------------------------------------------------------------------------------------------------------

worksystem

Raspberry 4 
Raspberry PI OS 64bit
Python 3.12.4

**Comment by laneboyerre** [comment]
Hi there,

Thank you for reporting this issue. The error message indicates that the `_tkinter` module is missing. This module is required for `tkinter` to work and is often not included by default in some Python installations. 

Here are the steps to resolve this issue on a Raspberry Pi running Raspberry Pi OS 64-bit:

1. **Update your package list**:
    ```bash
    sudo apt update
    ```

2. **Install the Tkinter package**:
    ```bash
    sudo apt install python3-tk
    ```

3. **Verify the installation**:
    - Open a Python shell by running `python3` in your terminal.
    - Try to import `tkinter` with the following command:
      ```python
      import tkinter as tk
      ```
    - If there are no errors, the installation was successful.

4. **Re-run your application**:
    ```bash
    python3 /home/dks384/meshtastic_chat_desktop/meshtastic_chat_desktop.py
    ```

These steps should resolve the issue. Please let me know if you encounter any further problems.

Best regards,
Lane
